name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '3 2 * * 1-5'
    - cron:  '42 4 * * 6'
    - cron:  '19 3 * * 0'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python==4.5.4.60
          pip install easyocr pillow numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: run
        run: perl -le 'sleep rand 1000' && STD_ID=${{ secrets.STD_ID }} PASSWORD=${{ secrets.PASSWORD }} python3 main.py
